name       : json-c
version    : '0.15'
release    : 12
source     :
    - https://github.com/json-c/json-c/archive/refs/tags/json-c-0.15-20200726.tar.gz : 4ba9a090a42cf1e12b84c64e4464bb6fb893666841d5843cc5bef90774028882
license    : MIT
component  : system.base
emul32     : yes
summary    : JSON implementation in C
description: |
    JSON-C implements a reference counting object model that allows you to easily construct JSON objects in C, output them as JSON formatted strings and parse JSON formatted strings back into the C representation of JSON objects.
setup      : |
    %patch -p1 < $pkgfiles/avoid-invalid-free-when-ref_count.patch
    %cmake -DBUILD_STATIC_LIBS=OFF -DCMAKE_INSTALL_LIBDIR=%libdir% .
build      : |
    %make
install    : |
    %make_install
    # Provide compatibility for older Steam games
    ln -s libjson-c.so.5.1.0 $installdir/%libdir%/libjson.so.0
check      : |
    %make test
