name       : json-c
version    : 0.12.1
release    : 6
source     :
    - https://github.com/json-c/json-c/archive/json-c-0.12.1-20160607.tar.gz : 989e09b99ded277a0a651cd18b81fcb76885fea08769d7a21b6da39fb8a34816
license    :
    - MIT
summary    : JSON implementation in C
component  : programming.library
emul32     : yes
description: |
    JSON-C implements a reference counting object model that allows you to easily construct JSON objects in C, output them as JSON formatted strings and parse JSON formatted strings back into the C representation of JSON objects.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    # Provide compatibility for older Steam games
    ln -s libjson-c.so.2.0.2 $installdir/%libdir%/libjson.so.0
