name        : json-c
version     : 0.12
release     : 4
source      :
    - https://s3.amazonaws.com/json-c_releases/releases/json-c-0.12.tar.gz : 000c01b2b3f82dcb4261751eb71f1b084404fb7d6a282f06074d3c17078b9f3f
license     :
    - MIT
summary     : JSON implementation in C
builddeps   :
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
description : |
    JSON-C implements a reference counting object model that allows you to easily construct JSON objects in C, output them as JSON formatted strings and parse JSON formatted strings back into the C representation of JSON objects.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
