name       : json-c
version    : 0.13
release    : 9
source     :
    - https://github.com/json-c/json-c/archive/json-c-0.13-20171207.tar.gz : 26e642456caab38aa9459279b9712ffec52f751e9f46641d28461c244bd6bae6
license    : MIT
component  : programming.library
emul32     : yes
summary    : JSON implementation in C
description: |
    JSON-C implements a reference counting object model that allows you to easily construct JSON objects in C, output them as JSON formatted strings and parse JSON formatted strings back into the C representation of JSON objects.
setup      : |
    %patch -p1 < $pkgfiles/avoid-invalid-free-when-ref_count.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    # Provide compatibility for older Steam games
    ln -s libjson-c.so.3.0.1 $installdir/%libdir%/libjson.so.0
check      : |
    %make check
